# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county',
            new_name='country',
        ),
    ]
