# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-01-08 11:00
=======
# Generated by Django 1.11.7 on 2017-12-18 15:36
>>>>>>> 91537c5eaa003beff4a98cefe8318e7918c86fa4
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_product_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
<<<<<<< HEAD
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
=======
                ('timestamp', models.DateTimeField(auto_now_add=True)),
>>>>>>> 91537c5eaa003beff4a98cefe8318e7918c86fa4
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
